# Generated by Django 5.2.5 on 2025-08-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardingSchedules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_type", models.CharField(max_length=20)),
                ("unavailable_time", models.DateTimeField()),
            ],
            options={
                "db_table": "boarding_schedules",
            },
        ),
        migrations.CreateModel(
            name="GroomingSchedules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("unavailable_time", models.TimeField()),
            ],
            options={
                "db_table": "grooming_schedules",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.IntegerField()),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="ReservationBoarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_id", models.CharField(max_length=20, unique=True)),
                ("store_name", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=20)),
                ("user_phone", models.CharField(max_length=15)),
                ("pet_name", models.CharField(max_length=10)),
                ("room_type", models.CharField(max_length=20)),
                ("checkin_date", models.DateTimeField()),
                ("checkout_date", models.DateTimeField()),
                ("customer_note", models.TextField(blank=True)),
                ("store_note", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reservation_boarding",
            },
        ),
        migrations.CreateModel(
            name="ReservationGrooming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_id", models.CharField(max_length=20, unique=True)),
                ("store_name", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=20)),
                ("user_phone", models.CharField(max_length=15)),
                ("grooming_services_name", models.JSONField(default=list)),
                ("pet_name", models.CharField(max_length=10)),
                ("pet_type", models.CharField(max_length=10)),
                ("pet_breed", models.CharField(max_length=10)),
                ("pick_up_service", models.BooleanField()),
                ("reservation_time", models.DateTimeField()),
                ("customer_note", models.TextField(blank=True)),
                ("store_note", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reservation_grooming",
            },
        ),
    ]
