# Generated by Django 5.2.5 on 2025-08-11 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="reservation_boarding",
            field=models.ForeignKey(
                blank=True,
                db_column="reservation_boarding_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.reservationboarding",
            ),
        ),
        migrations.AddField(
            model_name="boardingschedules",
            name="reservation_boarding_id",
            field=models.ForeignKey(
                db_column="reservation_boarding_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.reservationboarding",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="reservation_grooming",
            field=models.ForeignKey(
                blank=True,
                db_column="reservation_grooming_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.reservationgrooming",
            ),
        ),
        migrations.AddField(
            model_name="groomingschedules",
            name="reservation_grooming_id",
            field=models.ForeignKey(
                db_column="reservation_grooming_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.reservationgrooming",
            ),
        ),
    ]
