# Generated by Django 5.2.5 on 2025-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingschedules",
            name="store_name",
            field=models.CharField(default="毛孩子寵物美容", max_length=50),
            preserve_default=False,
        ),
    ]
