# Generated by Django 5.2.5 on 2025-08-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_boardingschedules_store_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationboarding",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservationgrooming",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
