# Generated by Django 5.2.5 on 2025-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_alter_reservationboarding_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationgrooming",
            name="grooming_period",
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservationgrooming",
            name="pet_size",
            field=models.CharField(default="小型", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservationgrooming",
            name="total_price",
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
