# Generated by Django 5.2.5 on 2025-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_reservationgrooming_grooming_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="blacklist",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="status",
            field=models.CharField(default="confirmed", max_length=20),
        ),
    ]
