# Generated by Django 5.2.5 on 2025-08-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_orders_blacklist_orders_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationboarding",
            name="total_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
