# Generated by Django 5.2.5 on 2025-08-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_reservationboarding_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationboarding",
            name="boarding_durations",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservationboarding",
            name="pick_up_service",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="blacklist",
            field=models.BooleanField(default=False),
        ),
    ]
