# Generated by Django 5.2.5 on 2025-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_reservationboarding_boarding_durations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationboarding",
            name="pick_up_service",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reservationgrooming",
            name="pick_up_service",
            field=models.BooleanField(default=False),
        ),
    ]
