# Generated by Django 5.2.5 on 2025-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0009_alter_reservationboarding_pick_up_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationgrooming",
            name="pet_breed",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
