# Generated by Django 5.2.5 on 2025-08-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_alter_reservationgrooming_pet_breed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="reservation_boarding",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="reservation_grooming",
        ),
        migrations.AddField(
            model_name="orders",
            name="reservation_boarding_id",
            field=models.CharField(
                blank=True,
                db_column="reservation_boarding_id",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="reservation_grooming_id",
            field=models.CharField(
                blank=True,
                db_column="reservation_grooming_id",
                max_length=50,
                null=True,
            ),
        ),
    ]
