# Generated by Django 5.2.5 on 2025-08-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_alter_orders_reservation_boarding_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="reservation_boarding_id",
            field=models.CharField(
                blank=True,
                db_column="reservation_boarding_id",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="reservation_grooming_id",
            field=models.CharField(
                blank=True,
                db_column="reservation_grooming_id",
                max_length=50,
                null=True,
            ),
        ),
    ]
