# Generated by Django 5.2.5 on 2025-08-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0013_alter_orders_reservation_boarding_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="user_id",
            field=models.CharField(max_length=50),
        ),
    ]
