# Generated by Django 5.2.5 on 2025-08-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0014_alter_orders_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(default="finished", max_length=20),
        ),
    ]
