# Generated by Django 5.2.5 on 2025-08-11 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardingRoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("cat", "Cat"), ("dog", "Dog")], max_length=10
                    ),
                ),
                ("room_type", models.CharField(max_length=100)),
                ("room_count", models.IntegerField()),
                ("pet_available_amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BoardingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cleaning_frequency", models.CharField(max_length=32)),
                ("introduction", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GroomingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("cat", "Cat"), ("dog", "Dog")], max_length=10
                    ),
                ),
                ("service_title", models.CharField(max_length=64)),
                ("introduction", models.TextField(max_length=500)),
                ("notice", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GroomingServicePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pet_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fur_amount",
                    models.CharField(
                        choices=[
                            ("none", "無毛"),
                            ("short", "短毛"),
                            ("medium", "中毛"),
                            ("long", "長毛"),
                            ("other", "其他"),
                        ],
                        max_length=16,
                    ),
                ),
                ("pricing", models.IntegerField()),
                ("grooming_duration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BoardingRoomPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.IntegerField()),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[("day", "Day"), ("month", "Month")], max_length=10
                    ),
                ),
                ("pricing", models.IntegerField()),
                ("overtime_rate", models.IntegerField()),
                ("overtime_charging", models.BooleanField(default=False)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.boardingroomtype",
                    ),
                ),
            ],
        ),
    ]
