# Generated by Django 5.2.5 on 2025-08-11 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingservice",
            name="store_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stores.store"
            ),
        ),
        migrations.AddField(
            model_name="boardingroomtype",
            name="boarding_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.boardingservice",
            ),
        ),
        migrations.AddField(
            model_name="groomingservice",
            name="store_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stores.store"
            ),
        ),
        migrations.AddField(
            model_name="groomingservicepricing",
            name="grooming_service_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.groomingservice",
            ),
        ),
    ]
