# Generated by Django 5.2.5 on 2025-08-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardingroomtype',
            name='boarding_service',
        ),
        migrations.AddField(
            model_name='boardingservice',
            name='notice',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='boardingservice',
            name='pet_available_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardingservice',
            name='room_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardingservice',
            name='room_type',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='boardingservice',
            name='species',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='dog', max_length=10),
        ),
        migrations.AlterField(
            model_name='boardingservice',
            name='introduction',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='groomingservice',
            name='notice',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='BoardingServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(choices=[('day', 'Day'), ('month', 'Month')], max_length=10)),
                ('pricing', models.IntegerField()),
                ('overtime_rate', models.IntegerField()),
                ('overtime_charging', models.BooleanField(default=False)),
                ('boarding_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.boardingservice')),
            ],
        ),
        migrations.DeleteModel(
            name='BoardingRoomPricing',
        ),
        migrations.DeleteModel(
            name='BoardingRoomType',
        ),
    ]
