# Generated by Django 5.2.5 on 2025-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_boardingroomtype_boarding_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardingservicepricing",
            name="overtime_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
