# Generated by Django 5.2.5 on 2025-08-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_boardingservicepricing_overtime_rate"),
        ("stores", "0003_alter_store_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardingservice",
            name="store_id",
            field=models.ForeignKey(
                db_column="store_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="groomingservice",
            name="store_id",
            field=models.ForeignKey(
                db_column="store_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
    ]
