# Generated by Django 5.2.5 on 2025-08-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=500)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="posts/"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("grooming", "Grooming"),
                            ("boarding", "Boarding"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("repending", "Repending"),
                            ("rechecked", "Rechecked"),
                            ("confirmed", "Confirmed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, null=True)),
                (
                    "reject_content",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                ("address", models.JSONField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("staff_number", models.IntegerField(blank=True, null=True)),
                ("pick_up_service", models.BooleanField(default=False)),
                ("grooming_service", models.BooleanField(default=False)),
                ("boarding_service", models.BooleanField(default=False)),
                ("boarding_pet_type", models.JSONField(blank=True, null=True)),
                (
                    "business_licences_url",
                    models.ImageField(blank=True, null=True, upload_to="stores/"),
                ),
                (
                    "boarding_license_dog_url",
                    models.ImageField(blank=True, null=True, upload_to="stores/"),
                ),
                (
                    "boarding_license_cat_url",
                    models.ImageField(blank=True, null=True, upload_to="stores/"),
                ),
                ("grooming_single_appointment", models.BooleanField(default=False)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="stores/"),
                ),
                ("daily_opening_time", models.TimeField(blank=True, null=True)),
                ("daily_closing_hours", models.TimeField(blank=True, null=True)),
                ("close_day", models.JSONField(blank=True, null=True)),
                ("service_item", models.JSONField(blank=True, null=True)),
                (
                    "traffic_info",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("repending", "Repending"),
                            ("rechecked", "Rechecked"),
                            ("confirmed", "Confirmed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reject_content",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_link", models.URLField(blank=True, null=True)),
                ("facebook_link", models.URLField(blank=True, null=True)),
                ("google_map_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoreImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="stores/"),
                ),
            ],
        ),
    ]
