# Generated by Django 5.2.5 on 2025-08-13 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="優惠券號碼"
                    ),
                ),
                (
                    "reservation_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="預約ID"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="訂單ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("used", "已使用"), ("not_used", "未使用")],
                        default="not_used",
                        max_length=20,
                        verbose_name="使用狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="user_id",
                        verbose_name="用戶ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "優惠券",
                "verbose_name_plural": "優惠券",
                "db_table": "coupons",
            },
        ),
    ]
