# Generated by Django 5.2.5 on 2025-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="store_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="店家ID"
            ),
        ),
    ]
