# Generated by Django 5.2.5 on 2025-08-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomersProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "男"), ("female", "女")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "customers_profile",
            },
        ),
        migrations.CreateModel(
            name="LikeStore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "like_store",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("cat", "貓"), ("dog", "狗")], max_length=4
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")], max_length=6
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=255, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=10, null=True)),
                ("fur_amount", models.CharField(max_length=10)),
                (
                    "spayed_or_neutered",
                    models.CharField(
                        choices=[("yes", "是"), ("no", "否"), ("uncertain", "不確定")],
                        default="uncertain",
                        max_length=10,
                    ),
                ),
                (
                    "microchip",
                    models.CharField(
                        choices=[("yes", "是"), ("no", "否"), ("uncertain", "不確定")],
                        default="uncertain",
                        max_length=10,
                    ),
                ),
                ("last_deworming_date", models.DateField(blank=True, null=True)),
                ("last_vaccine_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="pet_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pets",
            },
        ),
    ]
