# Generated by Django 5.2.5 on 2025-08-11 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customersprofile",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customersProfiles",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
        migrations.AddField(
            model_name="likestore",
            name="store_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stores.store"
            ),
        ),
        migrations.AddField(
            model_name="likestore",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likeStores",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="likestore",
            unique_together={("user_id", "store_id")},
        ),
    ]
