# Generated by Django 5.2.5 on 2025-08-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="last_deworming_date",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="last_vaccine_date",
        ),
    ]
