# Generated by Django 5.2.5 on 2025-08-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_pet_last_deworming_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customersprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
