# Generated by Django 5.2.5 on 2025-08-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customersprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
