# Generated by Django 5.2.5 on 2025-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_pet_breed_alter_pet_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="last_deworming_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="last_vaccine_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
