# Generated by Django 5.2.5 on 2025-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_alter_pet_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
