# Generated by Django 5.2.5 on 2025-08-15 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_remove_pet_last_deworming_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersprofile",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customersProfiles",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
    ]
